branch-defaults:
  default:
    environment: flashcube-stage
    group_suffix: null
environment-defaults:
  flashcube-dev:
    branch: null
    repository: null
global:
  application_name: flashcube
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: gardenof
  repository: null
  sc: null
  workspace_type: Application
