version: '3'

services:
  db:
    image: postgres
  web:
    build:
      context: ../../../
      dockerfile: ./devel/docker/flashcube/Dockerfile
    command: ./startup.sh
    ports:
      - "8000:8000"
    depends_on:
      - db