# Generated by Django 4.0.4 on 2022-05-19 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part_of_speech', models.CharField(choices=[('NN', 'NOUN'), ('PN', 'PRONOUN'), ('VB', 'VERB'), ('AJ', 'ADJECTIVE'), ('AD', 'ADVERB'), ('PR', 'PREPOSITION'), ('CJ', 'CONJUNCTION'), ('IJ', 'INTERJECTION')], max_length=2)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=2, null=True)),
                ('audio', models.FileField(null=True, upload_to='face_audio')),
                ('phonetic_spelling', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.category')),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.cube')),
            ],
            options={
                'ordering': ('cube', 'value'),
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='towers')),
                ('difficulty', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Expert')], default='B', max_length=1)),
                ('categories', models.ManyToManyField(related_name='tower_categories', to='towers.category')),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('push_notifications', models.BooleanField(default=True)),
                ('analytics', models.BooleanField(default=True)),
                ('categoriesOnboarded', models.BooleanField(default=False)),
                ('setsOnboarded', models.BooleanField(default=False)),
                ('onboardingSkipped', models.BooleanField(default=False)),
                ('baseCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_category', to='towers.category')),
                ('fluentCategories', models.ManyToManyField(blank=True, related_name='fluent_categories', to='towers.category')),
                ('learningCategories', models.ManyToManyField(blank=True, related_name='learning_categories', to='towers.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLearnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.face')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFaceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.face')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=5)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.category')),
            ],
        ),
        migrations.AddField(
            model_name='cube',
            name='towers',
            field=models.ManyToManyField(to='towers.tower'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('towers', models.ManyToManyField(blank=True, related_name='collection_towers', to='towers.tower')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(to='towers.category')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.tower')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tower')},
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('cubes', models.ManyToManyField(related_name='list_cubes', to='towers.cube')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'is_default')},
            },
        ),
    ]
