# Generated by Django 2.2.3 on 2019-07-29 17:12

from django.db import migrations

CATEGORIES = (
    'Arabic',
    'Bengali',
    'English',
    'French',
    'German',
    'Hindi',
    'Indonesian',
    'Italian',
    'Japanese',
    'Mandarin',
    'Portuguese',
    'Punjabi',
    'Russian',
    'Spanish',
)

def create_categories(apps, schema_editor):

    Category = apps.get_model('towers', 'Category')
    for c in CATEGORIES:
        category = Category.objects.create(category=c)
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories)
    ]
