# Generated by Django 2.2.3 on 2019-12-25 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('towers', '0012_body1_tower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='categories',
            field=models.ManyToManyField(related_name='tower_categories', to='towers.Category'),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarded', models.BooleanField(default=False)),
                ('onboardingSkipped', models.BooleanField(default=False)),
                ('baseCategory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_category', to='towers.Category')),
                ('learningCategories', models.ManyToManyField(blank=True, related_name='learning_categories', to='towers.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DL', "Don't Learn"), ('LN', 'Learn Now'), ('AL', 'Already Learned')], default='DL', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
