# Generated by Django 2.2.3 on 2020-01-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0016_auto_20191226_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='fluentCategories',
            field=models.ManyToManyField(blank=True, related_name='fluent_categories', to='towers.Category'),
        ),
    ]
