# Generated by Django 2.2.3 on 2020-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0017_userpreferences_fluentcategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='onboarded',
            new_name='categoriesOnboarded',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='setsOnboarded',
            field=models.BooleanField(default=False),
        ),
    ]
