# Generated by Django 2.2.3 on 2020-01-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0019_tower_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='difficulty',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Expert')], default='D', max_length=2),
        ),
    ]
