# Generated by Django 2.2.3 on 2020-05-19 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('towers', '0023_userlearnevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('user', 'is_default')},
        ),
    ]
