# Generated by Django 2.2.3 on 2020-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0027_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cube',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cubes'),
        ),
        migrations.AddField(
            model_name='cube',
            name='part_of_speech',
            field=models.CharField(choices=[('NN', 'NOUN'), ('PN', 'PRONOUN'), ('VB', 'VERB'), ('AJ', 'ADJECTIVE'), ('AD', 'ADVERB'), ('PR', 'PREPOSITION'), ('CJ', 'CONJUNCTION'), ('IJ', 'INTERJECTION')], default='NN', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='audio',
            field=models.FileField(null=True, upload_to='face_audio'),
        ),
        migrations.AddField(
            model_name='face',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='face',
            name='phonetic_spelling',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
