# Generated by Django 2.2.3 on 2020-06-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0030_auto_20200601_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
