version: 0.2

env:
  variables:
    DJANGO_SETTINGS_MODULE: 'flashcube.settings.build'

phases:
  install:
    runtime-versions: 
      python: 3.7
      nodejs: 10
    commands:
      - yum install -y which
      - wget https://www.sqlite.org/2019/sqlite-autoconf-3300100.tar.gz
      - tar xvfz sqlite-autoconf-3300100.tar.gz
      - cd sqlite-autoconf-3300100
      - ./configure
      - make
      - make install
      - sqlite3 --version
      - which sqlite3
      - cd ..
      - pip install -r flashcube/requirements.txt
  build:
    commands:
      - cd flashcube
      - python manage.py test
artifacts:
  files:
    - '**/*'
  base-directory: flashcube