version: 0.2
phases:
  install:
    runtime-versions: 
      python: 3.7
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python manage.py test
artifacts:
  files:
    - '**/*'
  base-directory: flashcube