version: 0.2

phases:
  install:
    runtime-versions: 
      python: 3.7
      nodejs: 10
    commands:
      - pip install -r flashcube/requirements.txt
  build:
    commands:
      - cd flashcube
      - python manage.py test
artifacts:
  files:
    - '**/*'
  base-directory: flashcube