version: 0.2

env:
  variables:
    DB_ENVIRONMENT: 'test'


phases:
  install:
    runtime-versions: 
      python: 3.7
      nodejs: 10
  pre_build:
    commands:
      - sudo yum install postgresql postgresql-server postgresql-devel postgresql-contrib
      - sudo postgresql-setup initdb
      - sudo service postgresql start
      - pip install -r flashcube/requirements.txt
  build:
    commands:
      - cd flashcube
      - printenv
      - python manage.py test
artifacts:
  files:
    - '**/*'
  base-directory: flashcube