version: 0.2

env:
  variables:
    DJANGO_SETTINGS_MODULE: 'flashcube.settings.build'

phases:
  install:
    runtime-versions: 
      python: 3.8
    commands:
      - pip install -r flashcube/requirements.txt
  build:
    commands:
      - cd flashcube
      - python manage.py test
artifacts:
  files:
    - '**/*'
  base-directory: flashcube