# Generated by Django 2.2.3 on 2019-12-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0015_auto_20191226_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='learningCategories',
            field=models.ManyToManyField(blank=True, related_name='learning_categories', to='towers.Category'),
        ),
    ]
