# Generated by Django 2.2.3 on 2020-01-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0018_auto_20200107_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
