# Generated by Django 2.2.3 on 2020-05-27 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('towers', '0025_auto_20200519_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='towers'),
        ),
        migrations.CreateModel(
            name='UserFaceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.Face')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=5)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.Category')),
            ],
        ),
    ]
