# Generated by Django 2.2.3 on 2020-05-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0026_auto_20200527_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('towers', models.ManyToManyField(blank=True, related_name='collection_towers', to='towers.Tower')),
            ],
        ),
    ]
