# Generated by Django 2.2.3 on 2020-05-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0028_auto_20200528_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=2, null=True),
        ),
    ]
