# Generated by Django 2.2.3 on 2020-06-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0029_auto_20200528_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
